package com.hzvtc.hzssc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTotal(java.lang.Integer total) {
		set("total", total);
		return (M)this;
	}
	
	public java.lang.Integer getTotal() {
		return getInt("total");
	}

	public M setResidu(java.lang.Integer residu) {
		set("residu", residu);
		return (M)this;
	}
	
	public java.lang.Integer getResidu() {
		return getInt("residu");
	}

	public M setSize(java.lang.String size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.String getSize() {
		return getStr("size");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

}
