package com.hzvtc.hzssc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudents<M extends BaseStudents<M>> extends Model<M> implements IBean {

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}
	
	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setClassName(java.lang.String className) {
		set("class_name", className);
		return (M)this;
	}
	
	public java.lang.String getClassName() {
		return getStr("class_name");
	}

	public M setGrade(java.lang.Integer grade) {
		set("grade", grade);
		return (M)this;
	}
	
	public java.lang.Integer getGrade() {
		return getInt("grade");
	}

}
