package com.hzvtc.hzssc.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("activity", "Id", Activity.class);
		arp.addMapping("admin", "Id", Admin.class);
		arp.addMapping("goods", "Id", Goods.class);
		arp.addMapping("students", "student_id", Students.class);
	}
}

