package com.hzvtc.hzssc.model;

import com.hzvtc.hzssc.model.base.BaseStudents;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Students extends BaseStudents<Students> {
	public static final Students dao = new Students().dao();
}
